### ISSUE TITLE
AddWorkDays

### ISSUE THREAD

**Issue by Diaskhan** [picolino/isdayoff#5]
Добрый день.

1.Вопрос можно ли сделать Sync методы ?
2.Можно ли адаптировать данную библиотеку для 4,8  net ?
3. Можно ли сделать функцию которая бы на входе давала 2 параметра.
1 параметр дата, 2 параметр количество рабочих  дней, возвращаемое значение Дата.
Функция называется AddWorkDays.

**Comment by picolino** [comment]
Добрый день @Diaskhan 

1. Вы можете сделать обёртку над `IsDayOff` с синхронными методами для доступа, используя, например, конструкцию `GetAwaiter().GetResult()` для синхронного выполнения асинхронного кода. Дополнительную информацию можно посмотреть в [этой статье](https://docs.microsoft.com/en-us/archive/msdn-magazine/2015/july/async-programming-brownfield-async-development). Поскольку основной функционал библиотеки основан на сетевом взаимодействии через HTTP - асинхронное выполнение кода крайне важно для эффективного распределения ресурсов.

2. Как указано в readme, целевой фреймворк для данной библиотеки - .net standard 2.0. Исходя из [данной таблицы совместимости](https://docs.microsoft.com/ru-ru/dotnet/standard/net-standard?tabs=net-standard-2-0#select-net-standard-version) вы можете использовать данную библиотеку с .net framework. 4.8. Они полностью совместимы.

3. Текущий API класса `IsDayOff` достаточно гибок для покрытия различных сценариев, я не вижу большого смысла в добавлении предлагаемого вами метода, можно использовать существующие перегрузки для достижения ваших целей. К тому же предлагаемый вами метод достаточно узкоспециализирован (посчитать количество рабочих дней из 2 параметра и вернуть только их, начиная с указанной в первом параметре даты, как я понял ваш запрос), а библиотека предназначена для широкого применения.
