### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by FoxTes** [picolino/isdayoff#6]
Hi
Using your library, I ran into a testing problem. 
Specifically, I wanted to mock your service. Okay, let's say there is no interface, but then why are the methods not virtual?

**Comment by picolino** [comment]
Thanks for your question, @FoxTes 

Honestly, I don't see any reasons to add abstraction layer on the `IsDayOff` class. It is completely useless in case of internal library code, and if only purpose of this interface is to make `IsDayOff` class itself be testible **from the outside** - I don't see value in this changes in library code itself. Same logic could be applied about vitrual methods.

One thing you can do to mock this 'service' is to write **wrapper** around `IsDayOff` class and abstraction (interface) for it, for example:

```cs
public interface IIsDayOffService
{
    Task<List<DayOffDateTime>> CheckYearAsync(int year);
}

public class IsDayOffService : IIsDayOffService
{
    public IsDayOff isDayOff;

    public IsDayOffService(IsDayOff isDayOff) // Inject real IsDayOff instance in this service
    {
        this.isDayOff = isDayOff;
    }

    public async Task<List<DayOffDateTime>> CheckYearAsync(int year)
    {
        return await isDayOff.CheckYearAsync(year);
    }
}

public class IsDayOffServiceMock : IIsDayOffService
{
    public async Task<List<DayOffDateTime>> CheckYearAsync(int year)
    {
        // TODO: Your mocked logic
       throw new NotImplementedException();
    }
}
```

It's a little bit more work you should do on your side in this case, but this is a pretty standard solution for test external libraries.
¯\\_(ツ)_/¯

**Comment by FoxTes** [comment]
The standard and competently correct solution is the interface.
Well, we'll have to make a crutch.

**Comment by picolino** [comment]
@FoxTes It's not so obvious, as you say. 
I recommend you to learn about this subject from different resources before saying so, for example:
https://www.youtube.com/watch?v=v6hP2MXoVrI
